server:
  port: 20231
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_demo_one?useSSL=false
    username: root
    password: MC@:(==ni2024
mybatis:
  type-aliases-package: mix.user.pojo
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS